### ISSUE TITLE
Averiguar cómo capturar audio

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Tecnologias-multimedia/intercom#1]
Capturar 44100 muestras/segundo, 16 bits/muestra, 2 canales. Escríbanse (por ahora, sólo por comprobar que la captura es correcta) las muestras en disco, sin cabecera usando el endian de la máquina.

**Comment by juanrdzbaeza** [comment]
Buenas, he encontrado bastante sobre captura de sonido utilizando raspberry pi, siempre nombran la aplicación [alsamixer](https://en.wikipedia.org/wiki/Alsamixer), con lo que podríamos guardar en un archivo el sonido capturado. [http://www.g7smy.co.uk/2013/08/recording-sound-on-the-raspberry-pi/](http://www.g7smy.co.uk/2013/08/recording-sound-on-the-raspberry-pi/)
