### ISSUE TITLE
Averiguar como realizar la transformada y comprimir el audio.

### ISSUE THREAD

**Issue by Jarh57** [Tecnologias-multimedia/intercom#5]
Pues como dice el título mismo, para orientar un poco a los que no pueden venir a clase. Ya tenemos como grabar, reprodur y enviar audio en tiempo real, así que por ahora lo siguiente sería a esa entrada de audio aplicarle la transformada "x" veces y comprimir el audio antes de enviarlo al receptor.
Para hacerlo, estamos investigando sobre la librería **[PyWavelets](http://www.pybytes.com/pywavelets/)**.

**Comment by vicente-gonzalez-ruiz** [comment]
Muy bien. ¿Habéis dado con alguna de tipo "integer"? (que tanto los datos de entrada (muestras de audio) como los de salida (coeficientes wavelet) sean números enteros? Esto os va a ayudar a aplicar la codificación por planos de bits.

**Comment by Rorikid** [comment]
hemos acabado por redondear la transformada basica de PyWavelets.

**Comment by vicente-gonzalez-ruiz** [comment]
Hola! Pues gracias.

No se si os habéis dado cuenta, pero he pedido que este año otro grupo de tec. multimedia continue con vuestro proyecto. Espero que esto no sea ningún inconveniente.

Hasta pronto!

**Comment by Jarh57** [comment]
ah!, no me había dado cuenta. Si, sin ningún problema, es que lo he visto y me ha dado por cerrarlo :sweat: :disappointed:

**Comment by vicente-gonzalez-ruiz** [comment]
:-)

Por cierto, los proyectos siguien siguiendo libres para toda la comunidad de software libre. Por supuesto, si alguno de vosotros quisiera seguir contribuyendo, no hay ningún problema.

Slds!
